version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  target-branch: node16
  ignore:
  - dependency-name: node
    versions:
    - ">= 17"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  target-branch: node14
  ignore:
  - dependency-name: node
    versions:
    - ">= 15"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
