version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: node14
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: node12
  ignore:
  - dependency-name: node
    versions:
    - ">= 13.a"
    - "< 14"
  - dependency-name: node
    versions:
    - ">= 14.a"
    - "< 15"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: node10
  ignore:
  - dependency-name: node
    versions:
    - ">= 12.a"
    - "< 13"
  - dependency-name: node
    versions:
    - ">= 13.a"
    - "< 14"
  - dependency-name: node
    versions:
    - ">= 14.a"
    - "< 15"
