version: 1
update_configs:
  - package_manager: "docker"
    directory: "/"
    target_branch: node12
    update_schedule: "daily"
    automerged_updates:
    - match:
        dependency_type: "all"
        update_type: "semver:patch"
